version: '3'

services:
  vue:
    build: .
    container_name: vue_app
    volumes:
      - ./:/var/www/laravelInertiaVue/
    restart: always
    ports:
      - 8089:80
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vue
    ports:
      - 3306:3306

  webdbadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8080:80
